# Main entrypoint of the workflow. 
# Please follow the best practices: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/best_practices.html,
# in particular regarding the standardized folder structure mentioned there. 

# rule all
rule all:
  input:
  output:

# rule efetch
rule efetch:
  input:
  output:

# rename_fasta_records
rule rename_fasta_records:
  input:
  output:

# rule split_multifasta
rule rsplit_multifasta:
  input:
  output:

# rule pharokka:
rule pharokka:
  input: 
    "{split_fastas}.fasta"
  output: 
    gff_file="{split_fastas}.gff"
    faa_file="{split_fastas}.faa"
  threads: config["threads"]
  log: "workflow/logs/pharokka.log"
  conda: 
  shell:
    """
    (tag=${{input}%.fasta};
	  string=${tag##*_};
	  echo $string;
	  pharokka -i {input} -l $string -o $tag -p $tag -t {threads}) &> {log}
    """


