accession_file:
  "/path/to/file/with/accessions"

threads: 92

k: [21,33,55,77,99,127]

# we still need this file
signatures:
  "/path/to/file/with/accessions representing a conserved protein group"

iqtree:
  bootstraps:
    1000